# Generated by Django 4.2.4 on 2024-04-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(default='Press Save Button To Backup Database', null=True)),
                ('number_of_backups', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Backup Database',
            },
        ),
    ]
